INSERT INTO Department VALUES
('Arabic','ARABIC')
,('Art History','ARTHIST')
,('Biochemistry','BIOCHEM')
,('Biology','BIOLOGY')
,('Biomedical Engineering','BME')
,('Civil and Environmental Egr','CEE')
,('Cell Biology','CELLBIO')
,('Chemistry','CHEM')
,('Child Policy','CHILDPOL')
,('Chinese','CHINESE')
,('Classical Studies','CLST')
,('Cell and Molecular Biology','CMB')
,('Computer Science','COMPSCI')
,('Cultural Anthropology','CULANTH')
,('Documentary Studies','DOCST')
,('Drama','DRAMA')
,('Dutch','DUTCH')
,('Electrical &amp; Computer Egr','ECE')
,('Economics','ECON')
,('Education','EDUC')
,('Engineering','EGR')
,('Energy','ENERGY')
,('English','ENGLISH')
,('Environment','ENVIRON')
,('Earth and Ocean Sciences','EOS')
,('Study of Ethics','ETHICS')
,('Evolutionary Anthropology','EVANTH')
,('Finance','FINANCE')
,('French','FRENCH')
,('German','GERMAN')
,('Global Health','GLHLTH')
,('Greek','GREEK')
,('Graduate Studies','GS')
,('Gender Sexuality &amp; Feminist St','GSF')
,('Hebrew','HEBREW')
,('Hindi','HINDI')
,('History','HISTORY')
,('Health Policy','HTHPOL')
,('Hungarian','HUNGARN')
,('Internatl Comparative Studies','ICS')
,('Interdisciplinary','IND')
,('Italian','ITALIAN')
,('Jewish Studies','JEWISHST')
,('Japanese','JPN')
,('Korean','KOREAN')
,('Latin American Studies','LATAMER')
,('Latin','LATIN')
,('Linguistics','LINGUIST')
,('Literature','LIT')
,('Liberal Studies','LS')
,('Management','MANAGEMT')
,('Marketing','MARKETNG')
,('Master of Arts in Teaching','MAT')
,('Mathematics','MATH')
,('Mechanical Engr/Materials Sci','ME')
,('Economics','MGRECON')
,('MPS','MPS')
,('Music','MUSIC')
,('Neurology','NEURO')
,('Neurobiology','NEUROBIO')
,('Neuroscience','NEUROSCI')
,('Philosophy','PHIL')
,('Physician Assistant Program','PHYASST')
,('Physical Education','PHYSEDU')
,('Physics','PHYSICS')
,('Policy Journalism and Media St','PJMS')
,('Practice-Oriented Education','POE')
,('Polish','POLISH')
,('Political Science','POLSCI')
,('Portuguese','PORTUGUE')
,('Philosophy','Politics')
,('Psychiatry','PSC')
,('Psychology','PSY')
,('Public Policy','PUBPOL')
,('Religion','RELIGION')
,('Research','RESEARCH')
,('Human Rights','RIGHTS')
,('Romanian','ROMANIAN')
,('Romance Languages','ROMLANG')
,('Romance Studies','ROMST')
,('Radiation Oncology','RON')
,('Russian','RUSSIAN')
,('Social Entrepreneurship','SOCENT')
,('Sociology','SOCIOL')
,('Spanish','SPANISH')
,('Statistical Science','STA')
,('Theater Studies','THEATRST')
,('Thesis','THESIS')
,('Visual Studies','VISUALST')
,('Writing','WRITING');
